### ISSUE TITLE
"zlib: invalid header"

### ISSUE THREAD

**Issue by Southclaws** [hhrutter/pdfcpu#2] opened 2017-09-21 09:00 UTC
The PDF I tried was an image-based PDF (scanned document).

Unfortunately I can't post the PDF file here, but maybe this will help:

```go
ERROR: 2017/09/21 09:56:29 read.go:1435: obj 10756: zlib: invalid header
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/hhrutter/pdfcpu/read.parseObjectStream(0xc4200c5050, 0x62b781, 0x30)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/read/read.go:250 +0xb42
github.com/hhrutter/pdfcpu/read.decodeObjectStreams(0xc420088660, 0xc4200c5178, 0x1)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/read/read.go:1457 +0x7cc
github.com/hhrutter/pdfcpu/read.dereferenceXRefTable(0xc420088660, 0x0, 0x0)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/read/read.go:1681 +0xbf
github.com/hhrutter/pdfcpu/read.PDFFile(0x7ffd9f46d02d, 0x22, 0xc42008a380, 0xc420088660, 0x0, 0x0)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/read/read.go:1735 +0x2c1
github.com/hhrutter/pdfcpu.Read(0x7ffd9f46d02d, 0x22, 0xc42008a380, 0x2, 0x2, 0x101000000000000)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/api.go:66 +0x43
github.com/hhrutter/pdfcpu.readAndValidate(0x7ffd9f46d02d, 0x22, 0xc42008a380, 0xed15575bd, 0xffffffff005c1976, 0x707cc0, 0xc4200c53b8, 0x7ffd9f4bdbaf, 0xc4200c53c8, 0x100407d13, ...)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/api.go:183 +0x4c
github.com/hhrutter/pdfcpu.readValidateAndOptimize(0x7ffd9f46d02d, 0x22, 0xc42008a380, 0xed15575bd, 0x5c1976, 0x707cc0, 0x722ae8, 0xc4200c55d0, 0x4bfba4, 0x1000000005e6960, ...)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/api.go:203 +0x7f
github.com/hhrutter/pdfcpu.Optimize(0x7ffd9f46d02d, 0x22, 0xc420088330, 0x26, 0xc42008a380, 0x5e68a0, 0xc420088301)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/api.go:225 +0x8e
github.com/hhrutter/pdfcpu.Process(0xc4200c5d48, 0xc420084d10, 0xc420088330)
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/process.go:128 +0x98
main.main()
	/home/southclaws/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:404 +0xbfb
```

**Comment by hhrutter** [comment] 2017-09-21 09:48
Hi, can you submit a test pdf in order to reproduce + your OS and Go Version. Thanks for raising this issue!

**Comment by Southclaws** [comment] 2017-09-21 10:01
I'll see if I can find a PDF I can submit, unfortunately the one it crashes on can't be shared for legal reasons. I'm running it on Ubuntu 16.

**Comment by Southclaws** [comment] 2017-09-21 10:09
Here is a PDF file that causes the above error: https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/458055/FOI06744_75460_Service_Inquiry.pdf

**Comment by hhrutter** [comment] 2017-09-21 10:31
Thanks. I'll look into it.

**Comment by hhrutter** [comment] 2017-09-22 21:58
It may not look like it but this PDF is encrypted. pdfcpu does not support encryption and should have exited gracefully which is fixed in version 0.0.5. Having said that encryption support and its scope is work in progress. I keep you posted.

**Comment by Southclaws** [comment] 2017-09-22 22:51
Ah okay, I didn't know. Thanks!

**Comment by hhrutter** [comment] 2017-10-11 15:52
@Southclaws 
pdfcpu V0.0.7 comes with encryption support.

**Comment by hhrutter** [comment] 2018-11-13 23:36
No, Let me have a look..

**Comment by hhrutter** [comment] 2018-11-14 10:55
Fixed and committed!
Thanks for reporting this and have fun 💚

**Closed by hhrutter** 2018-11-14 10:55 UTC

**Comment by briansorahan** [comment] 2018-11-14 14:44
@hhrutter Thanks for the very fast turnaround! I tested again and the error seems to be fixed.

**Comment by hhrutter** [comment] 2018-11-14 14:47
You got it!
You can drop me star if you like pdfpu and haven't done so already..

**Comment by briansorahan** [comment] 2018-11-15 17:31
Done!
