### ISSUE TITLE
import fails with panic

### ISSUE THREAD

**Issue by dhf0820** [hhrutter/pdfcpu#58] opened 2018-12-24 18:20 UTC
importing a tiff file that converts using tiff2pdf to a valid pdf (though does give warnings about the tiff file: TIFFReadDirectory: Warning, Unknown field with tag 33000 (0x80e8) encountered.

With pdfcpu import it fails with this:
pdfcpu import -vv  11.pdf 11.tiff
importing images into 11.pdf: [11.tiff]
Import config: A4 595x842 points, pos=full, dx=0, dy=0, scaling: 0.5 relative

11.pdf will be created
Fatal: unexpected panic attack: runtime error: index out of range

github.com/hhrutter/pdfcpu/pkg/api.Process.func1
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/api/process.go:48
runtime.call32
	/usr/local/go/src/runtime/asm_amd64.s:522
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:513
io/ioutil.readAll.func1
	/usr/local/go/src/io/ioutil/ioutil.go:30
runtime.call32
	/usr/local/go/src/runtime/asm_amd64.s:522
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:513
runtime.panicindex
	/usr/local/go/src/runtime/panic.go:44
github.com/hhrutter/pdfcpu/ccitt.(*pixelBuf).addRun
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:84
github.com/hhrutter/pdfcpu/ccitt.(*decoder).handleHorizontal
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:348
github.com/hhrutter/pdfcpu/ccitt.(*decoder).handleHorizontal-fm
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:578
github.com/hhrutter/pdfcpu/ccitt.(*decoder).decodeGroup4
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:589
github.com/hhrutter/pdfcpu/ccitt.(*decoder).decode
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:617
github.com/hhrutter/pdfcpu/ccitt.(*decoder).Read
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/ccitt/reader.go:631
bytes.(*Buffer).ReadFrom
	/usr/local/go/src/bytes/buffer.go:206
io/ioutil.readAll
	/usr/local/go/src/io/ioutil/ioutil.go:36
io/ioutil.ReadAll
	/usr/local/go/src/io/ioutil/ioutil.go:45
github.com/hhrutter/pdfcpu/tiff.Decode
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/tiff/reader.go:683
github.com/hhrutter/pdfcpu/pkg/pdfcpu.ReadTIFFFile
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/imageRead.go:437
github.com/hhrutter/pdfcpu/pkg/pdfcpu.createImageResource
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/stamp.go:819
github.com/hhrutter/pdfcpu/pkg/pdfcpu.NewPageForImage
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/pdfcpu/importImage.go:386
github.com/hhrutter/pdfcpu/pkg/api.ImportImages
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/api/api.go:1347
github.com/hhrutter/pdfcpu/pkg/api.Process
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/pkg/api/process.go:80
main.process
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:268
main.main
	/home/dhf/Development/go/src/github.com/hhrutter/pdfcpu/cmd/pdfcpu/main.go:116
runtime.main
	/usr/local/go/src/runtime/proc.go:201
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333

Another file fails with this:
 pdfcpu import -v  0.pdf 0.tiff
importing images into 0.pdf: [0.tiff]
Import config: A4 595x842 points, pos=full, dx=0, dy=0, scaling: 0.5 relative

0.pdf will be created
Fatal: ccitt: corrupt group4 data

Again this converts with tiff2pdf and I can merge them using pdfcpu merge creating a valid multipage pdf.

**Comment by hhrutter** [comment] 2018-12-24 21:38
There are quite some TIFF extensions out there and TIFF per se is a versatile image format.
You have stumbled upon a bug in the CCITT Reader that may or may not have been caused by the nature of your TIFF file. What you are reporting makes sense to me because for merging image stream decoding is not necessary. 

I am up to the challenge but I am afraid without a test.tiff that reproduces this I will have a hard time fixing this, 

Cheers

**Comment by dhf0820** [comment] 2018-12-26 06:30
Please send your contact information to me dhf0820@gmail.com. I can get you samples. We can discuss in private.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by hhrutter** [comment] 2018-12-27 23:18
Fixed and part of the next release.

**Comment by hhrutter** [comment] 2019-01-13 20:32
Fixed in v0.1.21

**Closed by hhrutter** 2019-01-13 20:32 UTC
