### ISSUE TITLE
Failed to merge

### ISSUE THREAD

**Issue by wode17** [hhrutter/pdfcpu#52] opened 2018-11-20 08:07 UTC
hi @hhrutter 
  It's great project!

 Now i have a question. The result of merging tow pdf file looks like not correct.
 the tow input file:
[test3.pdf](https://github.com/hhrutter/pdfcpu/files/2602389/test3.pdf)
[test4.pdf](https://github.com/hhrutter/pdfcpu/files/2602391/test4.pdf)

out file:
[out2.pdf](https://github.com/hhrutter/pdfcpu/files/2598663/out2.pdf)

code:
`
   filenamesIn := []string{"test3.pdf", "test4.pdf", "out2.pdf"}

    _, err := Process(MergeCommand(filenamesIn, "out.pdf", pdfcpu.NewDefaultConfiguration()))
    if err != nil {
        return
    }
`

for comparing, the output of [cpdf](https://community.coherentpdf.com/) : 
[out1.pdf](https://github.com/hhrutter/pdfcpu/files/2598670/out1.pdf)

**Comment by hhrutter** [comment] 2018-11-20 10:54
Hello!

Thanks for reporting this!
This is not a problem with pdfcpu merging.
The reason the output is not as expected is because pdfcpu still does not support UTF-8.

Before you merge you have to make sure `pdfcpu` is able to process your input correctly.
Just execute `pdfcpu optimize in.pdf out.pdf` and check out.pdf.
If out.pdf is looking good to you then there should not be a merging problem
but - like I just mentioned - UTF-8 support is yet to come.

If you can provide a very simple, small 1 page PDF with your (Chinese?) UTF-8 fonts that would help a lot in making pdfcpu UTF-8 ready!

**Comment by wode17** [comment] 2018-11-21 02:57
hi hhrutter

Thanks for reply!

Sorry for pasting the wrong input files.  Now I update the correct ones.

I will try it as you say.

This's a small 1 page PDF with 1 line of text using  Chinese. Hope it helps you testing the  new 
UTF-8 feature.
[demo-utf8.pdf](https://github.com/hhrutter/pdfcpu/files/2602451/demo-utf8.pdf)

**Comment by hhrutter** [comment] 2018-11-21 09:14
Thanks!
I am curious. 
Can you tell me what that means?

**Comment by wode17** [comment] 2018-11-21 14:59
It means "Hello, hhrutter". It's a friendly greeting in Chinese :)

**Comment by hhrutter** [comment] 2018-11-21 15:11
I checked your file with pdf optimize and it works. That means the problem is more complicated. 

Whatever simple one page sample file you can provide where the result file after doing pdfcpu optimize does not produce expected output will help. The simpler the content the better. 

Thanks so much for spending time on this!

**Comment by hhrutter** [comment] 2018-12-04 11:31
FYI I have fixed this!
It will go live by the end of the week.

**Comment by hhrutter** [comment] 2018-12-09 22:53
fixed with v0.1.19

**Closed by hhrutter** 2018-12-09 22:53 UTC
